### ISSUE TITLE
No super class method found for "decode"

### ISSUE THREAD

**Issue by jens321** [allenai/allennlp-demo#329]
When trying to run the backend for the demo on my local machine using `python3 app.py --model reading-comprehension`, I get the following error: 

```
Traceback (most recent call last):
  File "app.py", line 36, in <module>
    from server.models import load_demo_models
  File "/Users/jenstuyls/Desktop/research/allennlp-demo/server/models.py", line 6, in <module>
    import allennlp_rc
  File "/Users/jenstuyls/miniconda3/envs/allennlp_source/lib/python3.7/site-packages/allennlp_rc/__init__.py", line 2, in <module>
    import allennlp_rc.models
  File "/Users/jenstuyls/miniconda3/envs/allennlp_source/lib/python3.7/site-packages/allennlp_rc/models/__init__.py", line 3, in <module>
    from allennlp_rc.models.dialog_qa import DialogQA
  File "/Users/jenstuyls/miniconda3/envs/allennlp_source/lib/python3.7/site-packages/allennlp_rc/models/dialog_qa.py", line 24, in <module>
    class DialogQA(Model):
  File "/Users/jenstuyls/miniconda3/envs/allennlp_source/lib/python3.7/site-packages/allennlp_rc/models/dialog_qa.py", line 478, in DialogQA
    def decode(self, output_dict: Dict[str, torch.Tensor]) -> Dict[str, Any]:
  File "/Users/jenstuyls/miniconda3/envs/allennlp_source/lib/python3.7/site-packages/overrides/overrides.py", line 71, in overrides
    method.__name__)
AssertionError: No super class method found for "decode"
```

I am not sure what's causing this. I installed the editable version of allennlp as described here: https://github.com/allenai/allennlp (so version is allennlp 0.9.1-unreleased).

**System info:**
- Ubuntu 16.04.6 LTS

**Comment by matt-gardner** [comment]
That method was renamed to `make_output_human_readable`.  You're using a version of `allennlp_rc` that is incompatible with `allennlp`.  You either need to upgrade `allennlp_rc` or downgrade `allennlp`.

**Comment by jens321** [comment]
Currently I have the following versions: 
```
allennlp 0.9.1-unreleased          
allennlp-hub 0.0.1-unreleased
allennlp-reading-comprehension 0.0.1-unreleased
allennlp-semparse 0.0.1-unreleased
```

How could I move to a later version of `alllennlp_rc` (or is mine the latest)? If it is the latest, how would I moved down a version in `allennlp` given I installed it from source?

**Comment by matt-gardner** [comment]
The important thing is to look at the version of allennlp that's required by the commit of the reading comprehension repo that you're using, and install that commit.  You would find that here: https://github.com/allenai/allennlp-reading-comprehension/blob/14fc0a424441de1b1c9cba8745f678df447b407f/requirements.txt#L2.

**Comment by jens321** [comment]
Thanks!
