### ISSUE TITLE
Cannot read property 'captureException' of undefined:

### ISSUE THREAD

**Issue by dragon18456** [allenai/allennlp-demo#854]
I am trying to run the allennlp-demo right now and I just want to run the ui-only version of the website. I am able to build the docker correctly with docker-compose -f docker-compose.ui-only.yaml up --build. However, once I go to localhost:8080, I get the error on the right side:

Error
Cannot read property 'captureException' of undefined:
TypeError: Cannot read property 'captureException' of undefined
    at Promised (http://localhost:8080/main.d9f0cd.js:1538:63)
    at renderWithHooks (http://localhost:8080/main.d9f0cd.js:259407:18)
    at updateFunctionComponent (http://localhost:8080/main.d9f0cd.js:261778:20)
    at beginWork (http://localhost:8080/main.d9f0cd.js:263485:16)
    at HTMLUnknownElement.callCallback (http://localhost:8080/main.d9f0cd.js:248367:14)
    at HTMLUnknownElement.sentryWrapped (http://localhost:8080/main.d9f0cd.js:56910:23)
    at Object.invokeGuardedCallbackDev (http://localhost:8080/main.d9f0cd.js:248416:16)
    at invokeGuardedCallback (http://localhost:8080/main.d9f0cd.js:248478:31)
    at beginWork$1 (http://localhost:8080/main.d9f0cd.js:268381:7)
    at performUnitOfWork (http://localhost:8080/main.d9f0cd.js:267196:12)
    at workLoopSync (http://localhost:8080/main.d9f0cd.js:267124:5)
    at renderRootSync (http://localhost:8080/main.d9f0cd.js:267087:7)
    at performSyncWorkOnRoot (http://localhost:8080/main.d9f0cd.js:266710:18)
    at http://localhost:8080/main.d9f0cd.js:255749:26
    at unstable_runWithPriority (http://localhost:8080/main.d9f0cd.js:313995:12)
    at runWithPriority$1 (http://localhost:8080/main.d9f0cd.js:255698:10)
    at flushSyncCallbackQueueImpl (http://localhost:8080/main.d9f0cd.js:255744:9)
    at flushSyncCallbackQueue (http://localhost:8080/main.d9f0cd.js:255731:3)
    at scheduleUpdateOnFiber (http://localhost:8080/main.d9f0cd.js:266310:9)
    at dispatchAction (http://localhost:8080/main.d9f0cd.js:260561:5)
    at http://localhost:8080/main.d9f0cd.js:4465:13

The tabs on the left allows me to go between all of the tabs, but the right side is just a red error message with all of these error messages.

I have no idea why this is going wrong since it should just be sending the requests to the real website's backend right?

**Comment by dragon18456** [comment]
One thing that I noticed is that when I end the docker-compose, I get the error messages:

allennlp-demo_nginx_1 exited with code 0
allennlp-demo_ui_1 exited with code 1
allennlp-demo_tasks_1 exited with code 0
allennlp-demo_model_cards_1 exited with code 0

So I think that this error is something with the UI
