### ISSUE TITLE
Investigate recurrent error.

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp-demo#878]
This error is being throw ~500 times per day or so and should be investigated (and ideally resolved):

```
Traceback (most recent call last):
  File "server.py", line 20, in <module>
    from allennlp.models.archival import load_archive
  File "/usr/local/lib/python3.7/site-packages/allennlp/models/__init__.py", line 8, in <module>
    from allennlp.models.bert_for_classification import BertForClassification
  File "/usr/local/lib/python3.7/site-packages/allennlp/models/bert_for_classification.py", line 11, in <module>
    from allennlp.training.metrics import CategoricalAccuracy
  File "/usr/local/lib/python3.7/site-packages/allennlp/training/metrics/__init__.py", line 12, in <module>
    from allennlp.training.metrics.conll_coref_scores import ConllCorefScores
  File "/usr/local/lib/python3.7/site-packages/allennlp/training/metrics/conll_coref_scores.py", line 5, in <module>
    from sklearn.utils.linear_assignment_ import linear_assignment
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'
```

**Comment by leo-liuzy** [comment]
In allennlp repo, I see no file called `conll_coref_scores.py`
