### ISSUE TITLE
A few errors on 2.1

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#915]
Here is the environment I used:

```
 docker run -i -t --entrypoint bash -v $HOME/.allennlp:/root/.allennlp allennlp/models:v2.1.0-cuda11.0
```

## Reading Comprehension

Evaluation gave many WARNINGS:

```
allennlp evaluate         https://storage.googleapis.com/allennlp-public-models/bidaf-elmo.2021-02-11.tar.gz         https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-dev-v1.1.json
```

```
2021-03-31 21:38:06,697 - WARNING - spacy - [W108] The rule-based lemmatizer did not find POS annotation for the token 'who'. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
```

### Prediction

```
$ echo '{"question": "What game are they playing?", "image": "https://storage.googleapis.com/allennlp-public-data/vqav2/baseball.jpg"}' |     allennlp predict https://storage.googleapis.com/allennlp-public-models/vilbert-vqa-pretrained.2021-03-15.tar.gz -
...
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 33, in <module>
    sys.exit(load_entry_point('allennlp', 'console_scripts', 'allennlp')())
  File "/stage/allennlp/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/stage/allennlp/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/stage/allennlp/allennlp/commands/predict.py", line 224, in _predict
    predictor = _get_predictor(args)
  File "/stage/allennlp/allennlp/commands/predict.py", line 115, in _get_predictor
    archive = load_archive(
  File "/stage/allennlp/allennlp/models/archival.py", line 208, in load_archive
    model = _load_model(config.duplicate(), weights_path, serialization_dir, cuda_device)
  File "/stage/allennlp/allennlp/models/archival.py", line 242, in _load_model
    return Model.load(
  File "/stage/allennlp/allennlp/models/model.py", line 406, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device)
  File "/stage/allennlp/allennlp/models/model.py", line 348, in _load
    raise RuntimeError(
RuntimeError: Error loading state dict for VqaVilbert
	Missing keys: ['backbone.image_embeddings.embeddings.location_embeddings.bias']
	Unexpected keys: []
```

**Comment by dirkgr** [comment]
I'm pretty sure the warning has already been addressed.

**Comment by dirkgr** [comment]
It works in AllenNLP 2.2.0.
